- name: Ensure elasticsearch is running
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Ensure logstash is running
  service:
    name: logstash
    state: started
    enabled: yes

- name: Ensure Kibana is running
  service: 
    name: kibana
    state: started
    enabled: yes

